### ISSUE TITLE
Jeet

### ISSUE THREAD

**Issue by keegoid** [sergiokopplin/indigo#85] opened 2016-03-27 04:20 UTC
What do you think about using Jeet with Stylus?
https://github.com/mojotech/jeet

Love what you've done so far with indigo! Thanks for your great example. I'm really learning a lot from you.

**Comment by RnbWd** [comment] 2016-03-27 23:50
Honestly I love indigo and I'm making a portfolio blog with it - but I use postcss

https://github.com/postcss/postcss

Right now I've mixes of 50/50 compiling parts of stylus and slowly rewriting like minor things so that it's compatibility with... one of the countless modules one can use with postcss to do.. anything :stuck_out_tongue_closed_eyes:

**Comment by sergiokopplin** [comment] 2016-03-28 00:31
@keegoid, thank you for the comments.
I don't know jeet. I've heard about, but i didn't touch it yet.

The main porpuse of indigo is to be simple, really simple. I never thought of frameworks because i believe that indigo don't need them. What you think about?

**Comment by sergiokopplin** [comment] 2016-03-28 00:34
@RnbWd thank you for your words!

---

Yes, postcss is a great idea. No doubts about that.
I tried last week, but i'm not having time to apply postcss to the theme :cry:

---

I want to remove stylus because is getting slow sometimes, and that's a problem.
Do you have @RnbWd some kind of gulpfile ready to apply? Plugins and stuff?
Thank you!

**Comment by keegoid** [comment] 2016-03-28 12:58
@sergiokopplin postcss looks cool. I'm also interested in keeping it light, fast and easy to maintain. 
Looks like even the guy who made Jeet is now working with postcss ;)
https://github.com/peterramsing/lost

**Comment by RnbWd** [comment] 2016-03-28 14:38
I stopped working on it so I could focus on writing content and keep up to date with the current repo. It was difficult to maintain - if I can find the gulpfile I'll share it (but it might be lost) - but I explain what I did:

I compiled the styles into css with stylus - but I imported the styles into main.css using a postcss plugin. Then I replaced the variables with another postcss plugin - but that's when thing got difficult.  I converted it into something similar to SCSS. So maybe half of the stylus converted? I know it's possible to recreate it 100%, but it's difficult. There is a postcss-stylus parser that lets you use any postcss plugin with stylus - that's probably the best route to go IMO. The hardest part of using postcss is modularity and unexpected behavior - like there's at least 2-3 ways to use variables / imports - and it's confusing unless you design the parser (which is actually fun) . Bigger libraries are just built from modules. I think it's awesome - but it's hard to keep track of everything so I gave up :frowning:

**Comment by RnbWd** [comment] 2016-03-28 21:52
oh i just noticed you created a postcss branch :100: - I can help experiment with that if interested.

also I've been writing all my posts / editing / previewing the theme using electron apps - I added a menu bar (OS X) to go back to the main page because I don't know how to return to the site if I leave - but it's been a fun experience

**Comment by sergiokopplin** [comment] 2016-03-31 12:45
@keegoid, i'm sorry but i can't get interested in Jeet. I'm looking for postcss, that seems to be "the future".

---

@RnbWd: yes, i started with the branch, but just tests. I have to create it for real and apply for all the files. Do you know which pre-processor is the best for postcss?

---

I'm closing this, but we can keep talking about!
Thank you guys!

**Closed as completed by sergiokopplin** 2016-03-31 12:45 UTC
Labels: enhancement, help wanted, question
