### ISSUE TITLE
Not a recognized Liquid tag

### ISSUE THREAD

**Issue by w4h4z** [sergiokopplin/indigo#433] opened 2020-04-09 13:20 UTC
Your site is having problems building: The tag fa_svg on line 7 in _includes/footer.html is not a recognized Liquid tag. 

what must I do?

**Comment by kunalbotla** [comment] 2020-04-12 04:04
#416 is the same issue.

**Comment by sylvainmetayer** [comment] 2020-04-13 20:13
Indeed, this is a duplicate of #416, let's keep continue discussion there

**Closed as completed by sylvainmetayer** 2020-04-13 20:13 UTC
