### ISSUE TITLE
Why I can't post?

### ISSUE THREAD

**Issue by wkeiss** [sergiokopplin/indigo#274] opened 2018-01-20 04:37 UTC
I added an article to my _post but it can't be shown on my [site](https://wkeiss.github.io/blog/),I did these tries:

![image](https://user-images.githubusercontent.com/26640886/35179804-804a8c44-fddc-11e7-9ce4-d843adddfda5.png)

and I also  searched the issue , I found only one ( #88 )have similar question with me,but it was helpless....

I am really confused and have no idea how to do.
here is my [repository](https://github.com/wkeiss/wkeiss.github.io)for my blog,anyone can help me?

BTW
@sergiokopplin  I really really love Indigo Theme .Thanks so much for your building. : )

----------

【Update】

I cannot post because I used a number as a tag,which is supposed to be a string.So it's ok after I added double qoutes on the number.

**Comment by mehmandarov** [comment] 2018-01-20 05:59
That is quite likely because you haven't configured your repo to build GitHub Pages from the correct branch. Please check the GitHub [docs](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) for more details.

**Comment by wkeiss** [comment] 2018-01-20 06:16
Thanks a lot for your reply.I will check it later!Thanks again~

**Comment by wkeiss** [comment] 2018-01-20 11:10
from the Github [docs](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/)

> If your site is a User or Organization Page that has a repository named <username>.github.io or <orgname>.github.io, you cannot publish your site's source files from different locations. User and Organization Pages that have this type of repository name are **only published from the master branch**.

My page has already beed published from the master branch:

![image](https://user-images.githubusercontent.com/26640886/35182764-c06fb9d2-fe15-11e7-9d2e-bce0c524627f.png)

 I can't post...

**Comment by mehmandarov** [comment] 2018-01-21 21:41
How does it look when you run it locally, and not on github? I checked your repo now and it seems you were able to post now?

**Comment by wkeiss** [comment] 2018-01-22 04:18
I could post yesterday, but it couldn't post later.And also,there is issue in presenting my post.I don't know why...

![image](https://user-images.githubusercontent.com/26640886/35205089-9b18f1fe-ff6d-11e7-921b-7641c4d25cad.png)

the position of the title  should be like that:

![image](https://user-images.githubusercontent.com/26640886/35205116-c43a63f6-ff6d-11e7-91ef-27e78c87d7c3.png)

I'm going to run it locally.I will return feedback later.

@mehmandarov  You're so kind,thanks your help!

**Comment by wkeiss** [comment] 2018-01-22 04:54
**I ran it locally,it didn't work.** 

And I recieved the " page build faliure "email:
> The page build failed for the `master` branch with the following error:

>Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/.

>For information on troubleshooting Jekyll see:

  >https://help.github.com/articles/troubleshooting-jekyll-builds

Once  I could post,I just added another post and do nothing.But it is still fail to build my page. : (
I guess it 's because I use Windows...

**Comment by mehmandarov** [comment] 2018-01-22 17:05
It seems like a general issue with Jekyll, and not specifically with this theme. I would suggest you contact the proper support channels or forums for that.Since it is not an issue with this theme, I will be closing this issue. You are welcome to reopen it if you believe it is caused by this theme. However, it seems to be working fine here. I sincerely hope you will sort this out soon. :-)

**Closed as completed by mehmandarov** 2018-01-22 17:05 UTC
Labels: question

**Comment by wkeiss** [comment] 2018-01-25 02:02
Thanks for your suggestion. : )
