### ISSUE TITLE
Add Projects to project tab

### ISSUE THREAD

**Issue by vineelsai26** [sergiokopplin/indigo#431] opened 2020-04-08 09:15 UTC
how to add projects to projects tab like this
![Annotation 2020-04-08 144425](https://user-images.githubusercontent.com/52851879/78766978-a1d7df80-79a7-11ea-8d6b-eebe77604d46.png)

**Comment by kunalbotla** [comment] 2020-04-12 04:02
Make a duplicate of that one and you would be fine or you can use the tags that are listed in it. 
Also I don't think this is the type of thing you would open an issue for.

**Comment by sylvainmetayer** [comment] 2020-04-13 20:11
As @kuantingchen04 said, just copy the sample file and edit it to fit your need. Please reopen if you encounter any error while doing so.

**Closed as completed by sylvainmetayer** 2020-04-13 20:11 UTC
