### ISSUE TITLE
Liquid exception

### ISSUE THREAD

**Issue by weewey** [sergiokopplin/indigo#224] opened 2017-04-27 17:53 UTC
Running this on OSX

I have not made any edits to any files and trying to run 

```
bundle exec jekyll serve --config _config.yml,_config-dev.yml
```
returns me a liquid error

Liquid Exception: Liquid error (line 21): Invalid US-ASCII character "\xE2" on line 51 in /_layouts/default.html

**Comment by sergiokopplin** [comment] 2017-04-27 17:55
Can you put the '/_layouts/default.html' code here?

**Comment by weewey** [comment] 2017-04-27 17:56
```
---
layout: compress
---
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1">
    <meta name=viewport content="width=device-width, initial-scale=1">

    <meta name=description content="{{ site.bio }}">
    <meta name=author content="{{ site.name }}">

    {% seo %}
    
    {% include favicon.html %}

    <link rel="canonical" href="{{ site.url }}{{ page.url | replace:'index.html','' }}">
    <link rel="alternate" type="application/rss+xml" title="{{ site.title }}" href="{{ site.url }}{{ "/feed.xml" }}" />

    <style>
    {% capture scss_sheet %}{% include style.scss %}{% endcapture %}
    {{ scss_sheet | scssify }}
    </style>

</head>
<body>

    <div class="wrapper-{% if site.width == "normal" %}normal{% elsif site.width == "large" %}large{% endif %}">
        {% if page.tag %}
            <div class="post">
        {% else %}
            {% if showHeader != true %}
                <div class="page {{ page.title | downcase }}">
            {% else %}
                <div class="{{ page.title | downcase }}">
            {% endif %}
        {% endif %}

            {{ content }}
        </div>
    </div>

    {% include icons.html %}

    {% include analytics-google.html %}
</body>
</html>
```

**Comment by weewey** [comment] 2017-04-27 17:58
I have tried adding
```encoding : utf-8 ```
in _config.yml.

Saved default.html with utf-8 encoding.

But still having the issue

**Comment by sergiokopplin** [comment] 2017-04-27 17:59
Have you edited this file?

**Comment by weewey** [comment] 2017-04-27 17:59
nope, I have not.

**Comment by sergiokopplin** [comment] 2017-04-27 18:11
OK, i'll check this error later!

**Comment by weewey** [comment] 2017-04-27 18:27
Thanks!

**Comment by sagaciouszu** [comment] 2017-05-02 12:38
I'm having the same issue, same file and all.

**Comment by sergiokopplin** [comment] 2017-05-13 13:51
@weewey @sagaciouszu can you guys tell me what's the your system version? Also ruby.
Thanks

**Comment by sergiokopplin** [comment] 2017-07-04 14:04
Closing by now

**Closed as completed by sergiokopplin** 2017-07-04 14:04 UTC
Labels: question

**Comment by hessuman** [comment] 2017-07-27 20:17
I ran into this exactly same issue today on a new system.

In the end, I found out it was caused by  UTF-8 encoded characters in default.html (among several other files), while the environment on the server was set to ASCII. Fixed it by changing the environment variables to UTF-8.
